"""Constants for the steganographer application."""

import numpy as np

MAX_BITS_PER_PIXEL = 8
NUM_BITS = MAX_BITS_PER_PIXEL - 1
BIT_MAP = np.array([2 ** (NUM_BITS - 1 - i) for i in range(NUM_BITS)])

DEFAULT_DCT_BLOCK_SIZE = 8
DEFAULT_DCT_COEFFICIENT = 3
DEFAULT_DCT_QUANTIZATION_FACTOR = 10

DEFAULT_PRIVATE_KEY_SIZE = 2048
DEFAULT_IV_SIZE = 16
DEFAULT_AES_KEY_SIZE = 32
