name: Setup Node.js
description: Set up Node.js with npm cache and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"
        cache-dependency-path: python-steganographer-frontend/package-lock.json
    - name: Install dependencies
      shell: bash
      run: |
        cd python-steganographer-frontend
        npm ci
